apiVersion: v1
kind: Secret
metadata:
  name: openldap-secret
  namespace: openldap-ns
  labels:
    app: openldap
type: Opaque
stringData:
#  LDAP_PORT_NUMBER_KEY: "389"
# LDAP_ROOT_KEY: "dc=kube,dc=local"
  LDAP_ALLOW_ANON_BINDING_KEY: "no"
#  LDAP_LOGLEVEL_KEY: "0x8 conns"
  LDAP_ULIMIT_NOFILES_KEY: "1024"
  LDAP_ADMIN_USERNAME_KEY: "admin"
  LDAP_ADMIN_PASSWORD_KEY: "admin1"
  LDAP_USERS_KEY: "user"
  LDAP_PASSWORDS_KEY: "user1"
  ALLOW_EMPTY_PASSWORD_KEY: "no"
  LDAP_ENABLE_TLS_KEY: "no"
  LDAP_TLS_CERT_FILE_KEY: "/cert/openldap.crt"
  LDAP_TLS_KEY_FILE_KEY: "/cert/openldap.key"
  LDAP_TLS_CA_FILE_KEY: "/cert/openldapCA.crt"
