apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: openldap-volume-data-claim
  namespace: openldap-ns
spec:
  storageClassName: local-path
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: openldap-data-volume
