apiVersion: v1
kind: PersistentVolume
metadata:
  name: openldap-data-volume
  namespace: openldap-ns
spec:
  storageClassName: local-path
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/Users/sorriso/Documents/GitHub/kube-openldap-dockerhub/volume/data"
  capacity:
    storage: 1Gi
  claimRef:
    name: openldap-volume-data-claim
    namespace: openldap-ns
